import SwiftUI
import Combine

public class LocalizationManager: ObservableObject {
    public static let shared = LocalizationManager()

    @AppStorage("vessel_selected_locale") public var currentLocale: String = "tr" {
        didSet {
            objectWillChange.send()
        }
    }

    private let strings: [String: [String: String]] = [
        "en": [
            "nav_cinema": "Cinema",
            "nav_reading": "Manga & E-Books",
            "nav_live": "Live TV",
            "nav_library": "My Library",
            "nav_plugins": "Extensions",
            "nav_settings": "Settings",
            "nav_ai": "AI Discovery",
            "search_placeholder": "Search movies, series, manga, anime, TV channels...",
            "section_continue": "Continue Watching & Reading",
            "section_discover": "Discover",
            "btn_play": "Watch Now",
            "btn_read": "Read Now",
            "btn_add_library": "+ Add to Library",
            "btn_in_library": "✓ In Library",
            "btn_install": "Install",
            "btn_enable": "Enable",
            "btn_disable": "Disable",
            "btn_active": "Active",
            "iptv_guide_title": "Live TV Guide",
            "iptv_guide_subtitle": "Browse verified global channels by country & category",
            "plugins_title": "Extensions Hub",
            "plugins_subtitle": "Manage installed extensions and connect new catalogs",
            "plugins_tab_installed": "Installed Extensions",
            "plugins_tab_discover": "Discover & Install",
            "plugins_install_url_title": "Install via URL or Repo",
            "plugins_install_url_desc": "Paste extension manifest or Git repository URL",
            "plugins_install_local_title": "Install from Local Folder",
            "plugins_install_local_desc": "Specify path to extension executable or folder",
            "plugins_curated_title": "Curated Extensions",
            "plugins_curated_desc": "Official verified extensions for Vessel",
            "plugin_builtin": "Built-in",
            "plugin_external": "External Process",
            "settings_title": "Platform Settings",
            "settings_theme_title": "Theme Engine",
            "settings_theme_desc": "Pick built-in palettes or dynamic community themes",
            "settings_debrid_title": "Torrent & Debrid Cloud Streaming",
            "settings_debrid_desc": "Connect Real-Debrid or TorBox for high-speed cloud playback",
            "ai_badge_title": "Local AI Discovery Engine",
            "ai_main_headline": "Discover by Mood & Vibe",
            "ai_taste_summary": "Your Taste DNA calculated locally on device (100% Offline & Private).",
            "ai_btn_discover": "Find Matches",
            "ai_results_title": "AI Curated Matches",
            "ai_shelf_title": "✨ Tailored to Your Taste (AI Taste Match)",
            "ai_input_placeholder": "Describe what you want (e.g. 'mind-bending psychological anime', '90s cyberpunk')...",
            "ai_domain_all": "✨ All",
            "ai_domain_cinema": "🎬 Cinema & Series",
            "ai_domain_reading": "📖 Manga & Books",
            "ai_btn_close": "✕ Close",
            "ai_model_name": "Vessel-Embed-v2.4 (MiniLM-64D Core)",
            "mood_mind_bending": "Mind-Bending & Plot Twists",
            "mood_dark_cyberpunk": "Dark & Cyberpunk",
            "mood_cozy_wholesome": "Cozy & Chill",
            "mood_high_adrenaline": "Adrenaline & Epic Action",
            "mood_deep_mystery": "Deep Mystery & Crime",
            "mood_retro_classics": "Retro 80s & 90s",
            "trait_epic_action": "Epic Adventure & Action",
            "trait_mind_bending": "Mind-Bending & Plot Twist",
            "trait_dark_cyberpunk": "Dark Atmosphere & Cyberpunk",
            "trait_deep_mystery": "Deep Mystery & Detective",
            "trait_cozy_wholesome": "Cozy, Wholesome & Chill",
            "trait_scifi_space": "Sci-Fi & Cosmic Space",
            "trait_horror_thriller": "Horror & Psychological Thriller",
            "trait_anime_manga": "Immersive Anime & Manga"
        ],
        "tr": [
            "nav_cinema": "Sinema",
            "nav_reading": "Manga & E-Kitap",
            "nav_live": "Canlı TV",
            "nav_library": "Kütüphanem",
            "nav_plugins": "Eklentiler",
            "nav_settings": "Ayarlar",
            "nav_ai": "AI Keşif",
            "search_placeholder": "Film, dizi, manga, anime, TV kanalı ara...",
            "section_continue": "Kaldığın Yerden Devam Et",
            "section_discover": "Keşfet",
            "btn_play": "İzle",
            "btn_read": "Oku",
            "btn_add_library": "+ Kütüphaneye Ekle",
            "btn_in_library": "✓ Kütüphanede",
            "btn_install": "Kur",
            "btn_enable": "Etkinleştir",
            "btn_disable": "Devre Dışı",
            "btn_active": "Aktif",
            "iptv_guide_title": "Canlı TV / IPTV Rehberi",
            "iptv_guide_subtitle": "Doğrulanmış küresel kanalları ülkelere ve kategorilere göre keşfet",
            "plugins_title": "Eklenti Merkezi",
            "plugins_subtitle": "Yüklü eklentileri yönet ve yeni medya katalogları bağla",
            "plugins_tab_installed": "Yüklü Eklentiler",
            "plugins_tab_discover": "Eklenti Keşfet & Kur",
            "plugins_install_url_title": "URL veya Depo ile Kur",
            "plugins_install_url_desc": "Eklenti manifestosu veya Git deposu bağlantısı yapıştır",
            "plugins_install_local_title": "Yerel Klasörden Kur",
            "plugins_install_local_desc": "Eklenti yürütülebilir dosyası veya klasör yolu gir",
            "plugins_curated_title": "Önerilen Resmi Eklentiler",
            "plugins_curated_desc": "Vessel için onaylı ve güvenli eklentiler",
            "plugin_builtin": "Dahili (Gömülü)",
            "plugin_external": "Harici Süreç",
            "settings_title": "Platform Ayarları",
            "settings_theme_title": "Tema Motoru",
            "settings_theme_desc": "Dahili paletler veya topluluk temaları arasından seçim yap",
            "settings_debrid_title": "Torrent ve Debrid Bulut Akışı",
            "settings_debrid_desc": "Yüksek hızlı bulut akışı için Real-Debrid veya TorBox bağla",
            "ai_badge_title": "Yerel AI Keşif Motoru",
            "ai_main_headline": "Ruh Haline & Zevkine Göre Keşfet",
            "ai_taste_summary": "Kişisel zevk profiliniz yerel olarak hesaplandı (100% Çevrimdışı & Gizli).",
            "ai_btn_discover": "Öneri Getir",
            "ai_results_title": "Yapay Zeka Keşifleri",
            "ai_shelf_title": "✨ Senin Zevkine Özel (AI Taste Match)",
            "ai_input_placeholder": "Nasıl bir şey arıyorsun? (örn: 'ters köşe psikolojik anime', '90lar siberpunk')...",
            "ai_domain_all": "✨ Tümü",
            "ai_domain_cinema": "🎬 Sinema & Dizi",
            "ai_domain_reading": "📖 Manga & Kitap",
            "ai_btn_close": "✕ Kapat",
            "ai_model_name": "Vessel-Embed-v2.4 (MiniLM-64D Çekirdek)",
            "mood_mind_bending": "Zihin Yakan & Ters Köşe",
            "mood_dark_cyberpunk": "Karanlık & Siberpunk",
            "mood_cozy_wholesome": "Kafa Dağıtmalık & Huzurlu",
            "mood_high_adrenaline": "Adrenalin & Epik Aksiyon",
            "mood_deep_mystery": "Derin Gizem & Polisiye",
            "mood_retro_classics": "Retro 80'ler & 90'lar",
            "trait_epic_action": "Epik Macera & Aksiyon",
            "trait_mind_bending": "Zihin Yakan & Ters Köşe",
            "trait_dark_cyberpunk": "Karanlık Atmosfer & Siberpunk",
            "trait_deep_mystery": "Derin Gizem & Polisiye",
            "trait_cozy_wholesome": "Kafa Dağıtmalık & Huzurlu",
            "trait_scifi_space": "Bilim Kurgu & Uzay",
            "trait_horror_thriller": "Korku & Gerilim",
            "trait_anime_manga": "Sürükleyici Şonen / Seinen Anime"
        ],
        "de": [
            "nav_cinema": "Kino",
            "nav_reading": "Manga & E-Books",
            "nav_live": "Live-TV",
            "nav_library": "Bibliothek",
            "nav_plugins": "Erweiterungen",
            "nav_settings": "Einstellungen",
            "nav_ai": "KI-Entdeckung",
            "search_placeholder": "Filme, Serien, Manga, Anime suchen...",
            "section_continue": "Weiterschauen & Weiterlesen",
            "section_discover": "Entdecken",
            "btn_play": "Jetzt ansehen",
            "btn_read": "Jetzt lesen",
            "btn_add_library": "+ Zur Bibliothek",
            "btn_in_library": "✓ In Bibliothek",
            "btn_install": "Installieren",
            "btn_enable": "Aktivieren",
            "btn_disable": "Deaktivieren",
            "btn_active": "Aktiv",
            "iptv_guide_title": "Live-TV-Programm",
            "iptv_guide_subtitle": "Globale TV-Kanäle nach Land und Kategorie",
            "plugins_title": "Erweiterungs-Hub",
            "plugins_subtitle": "Installierte Erweiterungen verwalten",
            "plugins_tab_installed": "Installierte Erweiterungen",
            "plugins_tab_discover": "Erweiterungen entdecken",
            "ai_badge_title": "Lokale KI-Entdeckungsengine",
            "ai_main_headline": "Nach Stimmung & Vibe entdecken",
            "ai_taste_summary": "Dein Geschmacksprofil wird lokal auf dem Gerät berechnet.",
            "ai_btn_discover": "Treffer finden",
            "ai_results_title": "KI-Kuratierte Treffer",
            "ai_domain_all": "✨ Alle",
            "ai_domain_cinema": "🎬 Kino & Serien",
            "ai_domain_reading": "📖 Manga & Bücher",
            "mood_mind_bending": "Mind-Bending & Plot-Twists",
            "mood_dark_cyberpunk": "Dunkel & Cyberpunk",
            "mood_cozy_wholesome": "Gemütlich & Entspannend",
            "mood_high_adrenaline": "Adrenalin & Epische Action",
            "mood_deep_mystery": "Tiefes Mysterium & Krimi",
            "mood_retro_classics": "Retro 80er & 90er"
        ],
        "fr": [
            "nav_cinema": "Cinéma",
            "nav_reading": "Manga & Livres",
            "nav_live": "TV en direct",
            "nav_library": "Ma bibliothèque",
            "nav_plugins": "Extensions",
            "nav_settings": "Paramètres",
            "nav_ai": "Découverte IA",
            "search_placeholder": "Rechercher films, séries, mangas, animés...",
            "section_continue": "Reprendre la lecture",
            "section_discover": "Découvrir",
            "btn_play": "Regarder",
            "btn_read": "Lire",
            "btn_add_library": "+ Ajouter",
            "btn_in_library": "✓ Dans la bibliothèque",
            "btn_install": "Installer",
            "btn_enable": "Activer",
            "btn_disable": "Désactiver",
            "btn_active": "Actif",
            "ai_badge_title": "Moteur IA de découverte locale",
            "ai_main_headline": "Découvrir selon votre humeur",
            "ai_taste_summary": "Votre profil est calculé localement sur l'appareil.",
            "ai_btn_discover": "Trouver des pépites",
            "ai_results_title": "Recommandations IA",
            "ai_domain_all": "✨ Tous",
            "ai_domain_cinema": "🎬 Cinéma & Séries",
            "ai_domain_reading": "📖 Manga & Livres",
            "mood_mind_bending": "Casse-tête & Rebondissements",
            "mood_dark_cyberpunk": "Sombre & Cyberpunk",
            "mood_cozy_wholesome": "Réconfortant & Détente",
            "mood_high_adrenaline": "Adrénaline & Action Épique",
            "mood_deep_mystery": "Mystère Profond & Polar",
            "mood_retro_classics": "Rétro Années 80 & 90"
        ],
        "es": [
            "nav_cinema": "Cine",
            "nav_reading": "Manga y Libros",
            "nav_live": "TV en Vivo",
            "nav_library": "Mi Colección",
            "nav_plugins": "Extensiones",
            "nav_settings": "Configuración",
            "nav_ai": "Descubrimiento IA",
            "search_placeholder": "Buscar películas, series, manga, anime...",
            "section_continue": "Continuar viendo",
            "section_discover": "Descubrir",
            "btn_play": "Ver ahora",
            "btn_read": "Leer ahora",
            "btn_add_library": "+ Añadir",
            "btn_in_library": "✓ En Colección",
            "btn_install": "Instalar",
            "btn_enable": "Activar",
            "btn_disable": "Desactivar",
            "btn_active": "Activo",
            "ai_badge_title": "Motor IA de Descubrimiento Local",
            "ai_main_headline": "Descubre según tu Estado de Ánimo",
            "ai_taste_summary": "Tu perfil de gustos se calcula localmente.",
            "ai_btn_discover": "Buscar Coincidencias",
            "ai_results_title": "Recomendaciones de IA",
            "ai_domain_all": "✨ Todo",
            "ai_domain_cinema": "🎬 Cine y Series",
            "ai_domain_reading": "📖 Manga y Libros",
            "mood_mind_bending": "Mente Inquieta y Giros Inesperados",
            "mood_dark_cyberpunk": "Oscuro y Cyberpunk",
            "mood_cozy_wholesome": "Cálido y Relajante",
            "mood_high_adrenaline": "Adrenalina y Acción Épica",
            "mood_deep_mystery": "Misterio Profundo y Policial",
            "mood_retro_classics": "Retro Años 80 y 90"
        ],
        "az": [
            "nav_cinema": "Kino",
            "nav_reading": "Manqa & E-Kitab",
            "nav_live": "Canlı TV",
            "nav_library": "Kitabxanam",
            "nav_plugins": "Qoşmalar",
            "nav_settings": "Tənzimləmələr",
            "nav_ai": "AI Kəşf",
            "search_placeholder": "Film, serial, manqa, anime, TV axtar...",
            "section_continue": "Qaldığınız Yerdən Davam Edin",
            "section_discover": "Kəşf Edin",
            "btn_play": "İzlə",
            "btn_read": "Oxu",
            "btn_add_library": "+ Kitabxanaya Əlavə Et",
            "btn_in_library": "✓ Kitabxanadadır",
            "btn_install": "Quraşdır",
            "btn_enable": "Aktivləşdir",
            "btn_disable": "Deaktiv Et",
            "btn_active": "Aktiv",
            "ai_badge_title": "Lokal AI Kəşf Mühərriki",
            "ai_main_headline": "Əhval-ruhiyyə və Zövqə Görə Kəşf Edin",
            "ai_taste_summary": "Zövq DNT-niz cihazınızda lokal olaraq hesablanır.",
            "ai_btn_discover": "Uyğun Məzmunu Tap",
            "ai_results_title": "AI Tövsiyələri",
            "ai_domain_all": "✨ Hamısı",
            "ai_domain_cinema": "🎬 Kino & Serial",
            "ai_domain_reading": "📖 Manqa & Kitab",
            "mood_mind_bending": "Zehin Qarıxdıran & Tərs Künc",
            "mood_dark_cyberpunk": "Qaranlıq & Kiberpank",
            "mood_cozy_wholesome": "Rahatladıcı & Xoş",
            "mood_high_adrenaline": "Adrenalin & Epik Döyüş",
            "mood_deep_mystery": "Dərin Sirr & Detektiv",
            "mood_retro_classics": "80 və 90-lar Retro Klassika"
        ]
    ]

    private init() {}

    public func t(_ key: String) -> String {
        let loc = currentLocale
        if let val = strings[loc]?[key] {
            return val
        }
        if let val = strings["en"]?[key] {
            return val
        }
        return key
    }
}
